services:
  trainer:
    container_name: trainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./ray_results:/root/ray_results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - PYTHONPATH=/app/src
      - CUDA_VISIBLE_DEVICES=0
    shm_size: '16gb'

  tensorboard:
    container_name: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./ray_results:/logs:ro
    restart: unless-stopped
